# -*- coding: utf-8 -*-
"""analisis_ventas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cse-7ABfq_sJgHq2ObhFVT-vnaPQMIOl
"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Archivos CSV/ventas_productos.csv', sep=';')
df

import matplotlib.pyplot as plt

df['Precio_Total'] = df['Cantidad'] * df['Precio']

# Mostrar los primeros registros
print(df.head())

# Crear un gráfico de barras para visualizar el precio total por producto
plt.bar(df['Producto'], df['Precio_Total'])
plt.xlabel('Producto')
plt.ylabel('Precio Total')
plt.title('Precio Total por Producto')
plt.savefig('grafico_precios.png')  # Guardar el gráfico como PNG
plt.show()